version: "3"
services:
    tomato:
        build: .
        container_name: "tomato"
        volumes:
            - "./:/tomato/"
        restart:
            "always"
        command: ["echo", "yay"]
